### ISSUE TITLE
OpenAI eval enhancement

### ISSUE THREAD

**Issue by notmd** [tju01/ilm-eval#9]
- Add some statistics per model like avg accuracy, win count.
- Add the total test cases (right of the eval name).

**Comment by tju01** [comment]
I'm closing this issue since I removed the OpenAI Evals benchmark. See https://github.com/tju01/ilm-eval/pull/51#issuecomment-1646594067 for the reason why I removed it but basically it's just a bad benchmark compared to the other ones that I have now.
